Dzien04/alx/alx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("movies.urls") )
] + static( settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

Dzien04/alx/movies/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", startpage_response),
    path("list", movielist_response, name="movie_list"),
    path("movieadd", movieadd_response, name="movie_add"),
    path("list/<int:id>", moviedetails_response, name="movie_details"),

    # sciezki do widoków logowania
    path("login", auth_views.LoginView.as_view(), name="login" ),
    path("logut", auth_views.LogoutView.as_view(), name="logout" ),
    path("logout-done", logout_done)

]

Dzien04/alx/movies/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator

class Comment(models.Model):
    body = models.TextField()
    stars = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(5)])
    created = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey("Movie", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.stars} - {self.body}"

    class Meta:
        verbose_name = "Komentarz"
        verbose_name_plural = "Komentarze"


class Movie(models.Model):

    def check_title_len(s):
        if len(s.strip()) < 2:
            raise ValidationError(message="Za krótki tytuł")

    MPAA = (
        ("-","Brak"),
        ("PG-13","Za zgodą rodziców"),
        ("NC-17","Powyżej 17-go roku życia"),
    )

    def create_path(instance, filename):
        pass

    title = models.CharField(max_length=255, verbose_name="Tytuł", validators=[check_title_len])
    description = models.TextField(max_length=1024, verbose_name="Opis")
    released = models.DateField(verbose_name="Data premiery", null=True, blank=True)
    year = models.IntegerField(null=True, blank=True, editable=False)
    imdb = models.DecimalField(null=True, blank=True, verbose_name="Ocena", max_digits=4, decimal_places=2 )
    trailer = models.URLField(null=True,blank=True, verbose_name="Link do trailera")
    poster = models.ImageField(null=True, blank=True, verbose_name="Plakat", unique=False)
    mpaa_rating = models.CharField(max_length=100, choices=MPAA, default="-", verbose_name="Rating MPAA")

    created = models.DateTimeField(editable=False, auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                                   null=True, editable=False)

    def __str__(self):
        return f"{self.title} - {self.year if self.year else 'BRAK DATY'}"

    def save(self, *args, **kwargs):
        if self.released:
            self.year = self.released.year
        super(Movie, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Film"
        verbose_name_plural = "Filmy"

Dzien04/alx/movies/forms.py
# Definicja formularza

from django import forms
from .models import *

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = "__all__"

# formularz bez połaczenia z modelem bazodanowym
class ContactForm(forms.Form):
    SUBJECT_LIST = (
        (0, 'Issue'),
        (1, 'Error')
    )
    name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=255)
    urgent = forms.BooleanField(label="Sprawa pilna")
    message = forms.CharField(
        max_length=1024, widget=forms.Textarea(), help_text="Opisz dokładnie problem"
    )
    subject = forms.ChoiceField(choices=SUBJECT_LIST)

Dzien04/alx/movies/views.py
from django.shortcuts import render
from django.http.response import HttpResponse, Http404
from .models import *
from .forms import *
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings

from django.contrib.auth.decorators import login_required

# Create your views here.

def startpage_response(request):
    return HttpResponse("<br/>".join( dir(request) ) )

def movielist_response(request):
    all_movies = Movie.objects.all().order_by("title")
    return render(request, "movie-list.html",
                  context={"movies":all_movies,
                           "media_url": settings.MEDIA_URL } )

def moviedetails_response(request, id):
    # try:
    #     movie = Movie.objects.get(pk=id)
    #     print(movie)
    #     return HttpResponse(str(movie))
    # except:
    #     raise Http404("nie ma takiego filmu")
    movie_obj = get_object_or_404(Movie, pk=id)
    comments = Comment.objects.filter(movie=movie_obj)
    return render(request, "movie-details.html",
                  context={"movie": movie_obj,
                           "comments": comments})

@login_required()
def movieadd_response(request):
    #if not request.user.is_authenticated:
    #    return redirect(settings.LOGIN_URL)

    form = MovieForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        movie = form.save(commit=False)
        movie.created_by = request.user
        movie.save()
        return redirect(movielist_response)
    return render(request, "movie-add-2.html",
                  context={
                      "form" : form
                  })

def logout_done(request):
    return render(request, "logout-done.html")

Dzien04/alx/movies/templates/logout-done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Zostałem wylogowany</h1>
<a href="{% url 'movie_list' %}">Lista filmów</a>
</body>
</html>

Dzien04/alx/movies/templates/movie-add-1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>Dodaj film</h1>

<form method="post">
    {%  csrf_token %}
    <table border="1">
    {{ form }}
    </table>
    <button type="submit">Zapisz</button>
</form>

</body>
</html>

Dzien04/alx/movies/templates/movie-add-2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista filmów</title>

</head>
<body style="margin:10px;">

<p>

        <b>Witaj {{ user.username }}</b>
        <a href="{% url 'logout' %}">Logout</a>

    </p>

<form method="post" >
  {% csrf_token %}

  {{ form.non_field_errors }}

  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field.errors }}
    {{ hidden_field }}
  {% endfor %}

  <table border="1">
    {% for field in form.visible_fields %}
      <tr>
        <th>{{ field.label_tag }}</th>
        <td>
            <span style="color: red;">{{ field.errors }}</span>
          {{ field }}
          {{ field.help_text }}
        </td>
      </tr>
    {% endfor %}
  </table>

  <button type="submit">Submit</button>
</form>

</body>
</html>

Dzien04/alx/movies/templates/movie-details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista filmów</title>
</head>
<body>

<h2>Film</h2>
<ul>

    <li>
        <p>
            <b>{{ movie.title }} - {{ movie.year|default_if_none:"Brak danych" }}</b><br/>
            <i>{{ movie.description }}</i><br/>
            <small>MPAA: {{ movie.get_mpaa_rating_display }}</small><br/>
            {% if movie.poster|length > 0 %}
            <a target="_blank" href="{{ media_url }}{{ movie.poster }}">Poster</a>
            {% endif %}
        </p>

        <p>
            Komentarze:
            <ul>
                {% for comment in comments %}
                    <li>
                        {{ comment.body }} - gwiazdki: {{ comment.stars }}
                    </li>
                {% endfor %}
            </ul>
        </p>
    </li>

</ul>

</body>
</html>

Dzien04/alx/movies/templates/movie-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista filmów</title>
</head>
<body>

<h2>Lista filmów</h2>
<ul>

    {% for movie in movies %}
    <li>
        <p>
            <b>{{ movie.title }} - {{ movie.year|default_if_none:"Brak danych" }}</b><br/>
            <i>{{ movie.description }}</i><br/>
            <small>MPAA: {{ movie.get_mpaa_rating_display }}</small><br/>
            {% if movie.poster|length > 0 %}
            <a target="_blank" href="{{ media_url }}{{ movie.poster }}">Poster</a>
            {% endif %}
        </p>
    </li>
    {% endfor %}

</ul>

</body>
</html>